#!/bin/bash
# Fix lucide-react imports across all files

# Mapping of lucide-react icons to Heroicons
declare -A icon_map
icon_map["Bug"]="BugAntIcon"
icon_map["Target"]="ViewfinderCircleIcon"
icon_map["Shield"]="ShieldCheckIcon"
icon_map["AlertTriangle"]="ExclamationTriangleIcon"
icon_map["CheckCircle"]="CheckCircleIcon"
icon_map["XCircle"]="XCircleIcon"
icon_map["Clock"]="ClockIcon"
icon_map["RefreshCw"]="ArrowPathIcon"
icon_map["Filter"]="FunnelIcon"
icon_map["ChevronDown"]="ChevronDownIcon"
icon_map["ChevronUp"]="ChevronUpIcon"
icon_map["Play"]="PlayIcon"
icon_map["Pause"]="PauseIcon"
icon_map["Square"]="StopIcon"
icon_map["Eye"]="EyeIcon"
icon_map["Download"]="ArrowDownTrayIcon"
icon_map["Upload"]="ArrowUpTrayIcon"
icon_map["Search"]="MagnifyingGlassIcon"
icon_map["Settings"]="CogIcon"
icon_map["Zap"]="BoltIcon"
icon_map["TrendingUp"]="ArrowTrendingUpIcon"
icon_map["Activity"]="ChartBarIcon"
icon_map["Globe"]="GlobeAltIcon"
icon_map["FileText"]="DocumentTextIcon"
icon_map["Send"]="PaperAirplaneIcon"
icon_map["ExternalLink"]="ArrowTopRightOnSquareIcon"
icon_map["Copy"]="ClipboardIcon"
icon_map["Trash2"]="TrashIcon"
icon_map["Edit3"]="PencilIcon"
icon_map["Plus"]="PlusIcon"
icon_map["Server"]="ServerIcon"
icon_map["Link2"]="LinkIcon"
icon_map["Bell"]="BellIcon"
icon_map["BarChart3"]="ChartBarIcon"
icon_map["PieChart"]="ChartPieIcon"
icon_map["Calendar"]="CalendarIcon"
icon_map["DollarSign"]="CurrencyDollarIcon"
icon_map["Award"]="TrophyIcon"
icon_map["Crosshair"]="ViewfinderCircleIcon"
icon_map["Radar"]="SignalIcon"
icon_map["Cpu"]="CpuChipIcon"
icon_map["Layers"]="Squares2X2Icon"
icon_map["ChevronRight"]="ChevronRightIcon"
icon_map["ArrowUpRight"]="ArrowUpRightIcon"
icon_map["ArrowDownRight"]="ArrowDownRightIcon"
icon_map["MoreVertical"]="EllipsisVerticalIcon"
icon_map["X"]="XMarkIcon"
icon_map["Terminal"]="CommandLineIcon"
icon_map["Cloud"]="CloudIcon"
icon_map["Key"]="KeyIcon"
icon_map["Loader2"]="ArrowPathIcon"
icon_map["Container"]="CubeIcon"
icon_map["Network"]="GlobeAltIcon"
icon_map["FileSearch"]="MagnifyingGlassIcon"
icon_map["History"]="ClockIcon"
icon_map["Info"]="InformationCircleIcon"
icon_map["Mail"]="EnvelopeIcon"
icon_map["User"]="UserIcon"
icon_map["Users"]="UsersIcon"
icon_map["Home"]="HomeIcon"
icon_map["Code"]="CodeBracketIcon"
icon_map["Database"]="CircleStackIcon"
icon_map["Lock"]="LockClosedIcon"
icon_map["Unlock"]="LockOpenIcon"
icon_map["LogOut"]="ArrowRightOnRectangleIcon"
icon_map["LogIn"]="ArrowLeftOnRectangleIcon"
icon_map["Package"]="CubeIcon"
icon_map["Repeat"]="ArrowPathIcon"
icon_map["RotateCw"]="ArrowPathIcon"

echo "Icon mappings created"
for icon in "${!icon_map[@]}"; do
  echo "$icon -> ${icon_map[$icon]}"
done
